version: '2'
services:
  osp:
    container_name: ${CONTAINER_NAME}
    restart: always
    image: linuxmuster/osp:latest
    ports: 
      - 127.0.0.1:${LOCAL_PORT}:80 
    environment:
      - SCHOOLNAME=${SCHOOLNAME}
      - AUTHTYPE=${AUTHTYPE}
      - BASEDN=${BASEDN}
      - LMN_VERSION=${LMN_VERSION}
      - LDAPSERVER=${LDAPSERVER}
      - USERTREE=${USERTREE}
      - GROUPTREE=${GROUPTREE}
      - LDAPPORT=${LDAPPORT}
      - USERFILTER=${USERFILTER}
      - GROUPFILTER=${GROUPFILTER}
      - GROUPDELPREFIX=${GROUPDELPREFIX}

    volumes:
      - ./volumes/data:/var/www/html/data  
      - ./volumes/conf:/var/www/html/conf
      - ./volumes/lib/plugins:/var/www/html/lib/plugins
