#!/bin/bash

# Copying env file in place
if [ ! -f .env ]; then
	cp env.dist .env
fi

# Setting values in .env 
# Creating nginx configuration
ansible-playbook ansible-setup.yml
# Starting app
docker-compose up -d
# Configure app from environment delivered 
# by .env ans docker-compose.yml
CONTAINER_NAME=$(grep CONTAINER_NAME .env | awk -F= '{print $2}')
docker exec -it $CONTAINER_NAME osp-setup
# Stopping app
docker-compose down

# delete broken symlinks
find -L /etc/nginx/sites-enabled/ -type l | xargs rm
# restart nginx
/etc/init.d/nginx restart

echo "App configured. You can start your app by executing"
echo "  docker-compose up -d"
